---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: import vpc variables
      include_vars: vpc_setup

    - name: create a VPC 
      amazon.aws.ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        tenancy: dedicated
        dns_support: true
        dns_hostnames: true
        state: "{{state}}"
        tags:
          Name: "{{vpc_name}}"
      register: vpcout
    
    - name: Create public subnet 1 in zone1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{pub_sub1}}"
        az: "{{zone1}}"
        region: "{{region}}"
        map_public: true
        state: "{{state}}"
        tags:
          Name: pubsub1
      register: pubsub1_out