---
- name: setting up the ec2 stack
  hosts: localhost
  connection: local 
  gather_facts: false

  tasks:
    - name: importing the vpc and bastion variables
      include_vars: vars/vpc_setup

    - name: importing the vpc id's
      include_vars: vars/output_vars

    - name: importing vprostack setup variables
      include_vars: vars/vprostacksetup

    - name: creating login-key
      amazon.aws.ec2_key:
        name: login-key
        region: "{{region}}"
      register: loginkeyout

    - name: saving the login-key
      copy:
       content: "{{loginkeyout.key.private_key}}"
       dest: ./login-key.pem
      when: loginkeyout.changed == true

    - name: security group for elb
      amazon.aws.ec2_security_group:
        name: vprofile-elb-sg
        description: vprofile-elb-sg
        vpc_id: "{{vpc_id}}"
        region: "{{region}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: elb_out

    - name: security group for elb
      amazon.aws.ec2_security_group:
        name: vprofile-stack-sg
        description: vprofile-stack-sg
        vpc_id: "{{vpc_id}}"
        region: "{{region}}"
        purge_rules: false
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{elb_out,group_id}}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{bastionsgid}}" 
      register: vpro_stack_out

    - name: security group for elb
      amazon.aws.ec2_security_group:
        name: vprofile-stack-sg
        description: vprofile-stack-sg
        vpc_id: "{{vpc_id}}"
        region: "{{region}}"
        purge_rules: false
        rules: 
          - proto: all
            group_id: "{{vpro_stack_out.group_id}}"

        