---
- name: setting up the ec2 stack
  hosts: localhost
  connection: local 
  gather_facts: false

  tasks:
    - name: importing the vpc and bastion variables
      include_vars: vars/vpc_setup

    - name: importing the vpc id's
      include_vars: vars/output_vars

    - name: importing vprostack setup variables
      include_vars: vars/vprostacksetup

    - name: creating login-key
      amazon.aws.ec2_key:
        name: login-key
        region: "{{region}}"
      register: loginkeyout

    - name: saving the login-key
      copy:
       content: "{{loginkeyout.key.private_key}}"
       dest: ./login-key.pem
      when: loginkeyout.changed == true

    - name: security-group for elb
      amazon.aws.ec2_security_group:
        name: vprofile-elb-sg
        description: vprofile-elb-sg
        vpc_id: "{{vpc_id}}"
        region: "{{region}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: elb_out

    - name: security-group for vprofile-stack
      amazon.aws.ec2_security_group:
        name: vprofile-stack-sg
        description: vprofile-stack-sg
        vpc_id: "{{vpc_id}}"
        region: "{{region}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{elb_out.group_id}}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{bastionsgid}}"
      register: vpro_sg_out

    - name: security-group for elb
      amazon.aws.ec2_security_group:
        name: vprofile-stack-sg
        description: vprofile-stack-sg
        vpc_id: "{{vpc_id}}"
        region: "{{region}}"
        rules:
          - proto: all
            group_id: "{{vpro_sg_out.group_id}}"

    - name: creating nginx instance
      amazon.aws.ec2_instance:
        name: "nginx-instance"
        key_name: "login-key"
        instance_type: t2.micro
        image_id: "{{nginx_ami}}"
        region: "{{region}}"
        exact_count: 1
        wait: yes
        wait_timeout: 300
        vpc_subnet_id: "{{pirsub1_id}}"
        security_group: "{{vpro_sg_out.group_id}}"
        tags:
          Name: web01
      register: web01_out

    - name: creating tomcat instance
      amazon.aws.ec2_instance:
        name: "tomcat-instance"
        key_name: "login-key"
        instance_type: t2.micro
        image_id: "{{tomcat_ami}}"
        region: "{{region}}"
        exact_count: 1
        wait: yes
        wait_timeout: 300
        vpc_subnet_id: "{{pirsub1_id}}"
        security_group: "{{vpro_sg_out.group_id}}"
        tags:
          Name: app01
      register: app01_out

    - name: creating mysql instance
      amazon.aws.ec2_instance:
        name: "mysql-instance"
        key_name: "login-key"
        instance_type: t2.micro
        image_id: "{{mysql_ami}}"
        region: "{{region}}"
        exact_count: 1
        wait: yes
        wait_timeout: 300
        vpc_subnet_id: "{{pirsub1_id}}"
        security_group: "{{vpro_sg_out.group_id}}"
        tags:
          Name: db01
      register: db0101_out

    - name: creating memcached instance
      amazon.aws.ec2_instance:
        name: "memccache-instance"
        key_name: "login-key"
        instance_type: t2.micro
        image_id: "{{memcached_ami}}"
        region: "{{region}}"
        exact_count: 1
        wait: yes
        wait_timeout: 300
        vpc_subnet_id: "{{pirsub1_id}}"
        security_group: "{{vpro_sg_out.group_id}}"
        tags:
          Name: mc01
      register: mc01_out

    - name: creating rabbitmq instance
      amazon.aws.ec2_instance:
        name: "rabbitmq-instance"
        key_name: "login-key"
        instance_type: t2.micro
        image_id: "{{rmq_ami}}"
        region: "{{region}}"
        exact_count: 1
        wait: yes
        wait_timeout: 300
        vpc_subnet_id: "{{pirsub1_id}}"
        security_group: "{{vpro_sg_out.group_id}}"
        tags:
          Name: rmq01
      register: rmq01_out
    
        
