apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
        - name: vproapp
          image: udaymac/vproapp:latest
          ports:
          - containerPort: 8080
            name: vproapp-port
      initContainers:
        - name: init-db
          image: busybox
          command: ['sh', '-c', "until nslookup vprodb-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb-service; sleep 2; done"]
        
        - name: init-mc
          image: busybox
          command: ['sh', '-c', "until nslookup vpromc-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for memcache; sleep 2; done"]