apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
  namespace: default
spec:
  selector:
    app: vproapp 
  type: LoadBalancer
  ports:
    port: 80
    protocol: TCP
    targetPort: vproapp-port
   