apiVersion: v1
kind: Service
metadata:
  name: vprodb-service
  namespace: default
spec:
  selector:
    app: vprodb 
  type: ClusterIP
  ports:
  - name: vprodb 
    protocol: TCP
    port: 3306
    targetPort: vprodb-port