version: '3.8'
services:
  vprodb:
    build:
      context: ./Dockerfiles/db/
      dockerfile: Dockerfile
    image: udaymac/vprofiledb
    container_name: vprodb
    ports:
      - 3306:3306
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=accounts
      - MYSQL_USER=admin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  vpromem:
    image: memcached
    expose:
      - 11211:11211

  vprormq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    expose:
      - 15672:15672

  vproapp:
    build:
      context: ./Dockerfiles/app/
      dockerfile: Dockerfile
    image: udaymac/vproapp
    container_name: vproapp
    ports:
      - 8080:8080
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
    depends_on:
      vprodb:
        condition: service_healthy

  vproweb:
    build:
      context: ./Dockerfiles/web/
      dockerfile: Dockerfile
    image: udaymac/vproweb
    container_name: vproweb
    ports:
     - 80:80
    depends_on:
     - vproapp

volumes:
  vprodbdata: {}
  vproappdata: {}
