apiVersion: v1
kind: Service
metadata:
  name: vpromc-service
  namespace: default
spec:
  selector:
    app: vpromc
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 11211
    targetPort: vpromc-port