apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app 
    spec:
      containers:
      - name: nginx 
        image: nginx:latest
        ports:
        - containerPort: 80