apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-app
spec:
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: udaymac/vproapp
        ports:
        - containerPort: 8080
