apiVersion: v1
kind: Pod
metadata:
  name: vprofile-app
  labels:
    name: vprofile-app
spec:
  containers:
  - name: vprofile-app
    image: udaymac/vproapp:latest
    ports:
      - containerPort: 8080

--- 
kind: Service
apiVersion: v1
metadata:
  name:  Service Name
spec:
  selector:
    app:  Selector Label
  type:  LoadBalancer | ClusterIP | NodePort
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  8080
