apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test
  labels:
    app: web-app
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: MYAPP
        image: nginx/nginx
        ports:
        - name: web
          containerPort:  80
          protocol: TCP