apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  containers:
  - name: nginx
    image: mysql:latest
    ports:
    - containerPort: 3360
    volumeMounts:
    - name: test-volume
      mountPath: /test-pod
  volumes:
    - name: test-volume
      hostPath:
        path: /data